### ISSUE TITLE
Возвращается список из пустых словарей, если запрашивается только одна колонка

### ISSUE THREAD

**Issue by AlekseyGur** [WLM1ke/apimoex#18]
https://github.com/WLM1ke/apimoex/blob/1aa33b704125a82673a077336175ff49362ebb6f/apimoex/requests.py#L73

Если columns=('слово'), то ",".join(columns) = 'с,л,о,в,о'

Стоит написать что-то вроде:

```Python
query[f"{table}.columns"] = ",".join(columns) if isinstance(columns, tuple) and len(columns)>1 else str(columns)
```

**Comment by WLM1ke** [comment]
Согласно, сигнатуре функции:
https://github.com/WLM1ke/apimoex/blob/1aa33b704125a82673a077336175ff49362ebb6f/apimoex/requests.py#L39

Надо просто посылать, что написано - `Optional[Tuple[str, ...]]`, а `str`

**Comment by AlekseyGur** [comment]
Ох, пардон. Не догадался...

**Comment by WLM1ke** [comment]
Я рекомендую, поставить `mypy` и запускать с флажком `--strict` подобного рода штуки отлично отлавливаются.
