### ISSUE TITLE
Купить акции

### ISSUE THREAD

**Issue by nagayev** [WLM1ke/apimoex#2]
Спасибо за библиотеку.
Было бы круто иметь возможность купить акции.

**Comment by WLM1ke** [comment]
Как вы это себе представляете сделать? Вы торгуете через брокера. У каждого брокера свои правила: кто-то предоставляет API для торговли, а кто-то нет.

**Comment by nagayev** [comment]
@WLM1ke Не там issue открыл, извиняюсь)
