### ISSUE TITLE
Отставание свечей от реального времени

### ISSUE THREAD

**Issue by DBoyara** [WLM1ke/apimoex#20]
Привет! Попробовал апишку и запрос `https://iss.moex.com/iss/engines/futures/markets/forts/securities/SiZ2/candles.json?from=2022-11-24&interval=1&iss.reverse=true` отдает свечи с отставанием на 10 минут, т.е., например, в 19:00, я получаю последнюю свечу за 18:50. Может в курсе это баг или фича? Читал в доке что можно как-то делать подписку, но не написано как именно. Завел аккаунт и попробовал тот же запрос с Basic Auth как в доке, но эффект тот же. По вашей доке тоже не осознал есть ли возможность получать запросы в реальном времени

**Comment by WLM1ke** [comment]
Насколько я знаю, это фича - без отставания данные за деньги.

**Comment by DBoyara** [comment]
Ок, спасибо
