### ISSUE TITLE
get_board_history for UWGN always returs 0 entries

### ISSUE THREAD

**Issue by bashu** [WLM1ke/apimoex#30]
subj

**Comment by WLM1ke** [comment]
Не торгуются в основном режиме торгов (TBQR), так как переведены в категорию бумаг с [повышенным риском](https://www.moex.com/ru/issue.aspx?board=TQPI&code=UWGN&utm_source=www.moex.com&utm_term=UWGN)

**Comment by bashu** [comment]
hmm, can I use different boards? like this:

```python
apimoex.get_board_history(session, "UGWN", board="TQPI")
```

**Comment by WLM1ke** [comment]
Да, но я не рекомендую связываться с бумагами, которые не торгуются основном режиме. Это обычно откровенный шлак, который может перестать торговаться в любой момент
