### ISSUE TITLE
apimoex vs aiomoex

### ISSUE THREAD

**Issue by greg-kan** [WLM1ke/apimoex#36]
Здравствуйте.
 
Через асинхронные запросы (aiomoex) работает быстрее.

Но не является ли испльзование асинхронных запросов некоторым "злоупотреблением" и, в том числе, поэтому был создан apimoex?

**Comment by WLM1ke** [comment]
Не очень понял, что за злоупотребление. А так сначала был создан apimoex, когда я только начинал изучать программирование и только потом aiomoex, когда изучил чуть побольше

**Comment by greg-kan** [comment]
Спасибо, большое.
Все понятно.
