### ISSUE TITLE
Запросы самого верхнего уровня по акциям и облигациям

### ISSUE THREAD

**Issue by greg-kan** [WLM1ke/apimoex#37]
Здравствуйте.
Прошу прощения - вопрос не по коду и это, собственно, не issue, но все же спрошу:

Интересуют, допустим, только акции и облигации.
Чтобы получить сначала общие сведенья об этих инструментах (чтобы впоследствии получить большую деталлизацию: историю, рыночные данные), насколько корректно делать первоначально запросы так:
https://iss.moex.com/iss/securities.json?engine=stock&market=shares  - акции
https://iss.moex.com/iss/securities.json?engine=stock&market=bonds - облигации

?

Напрпимер вот такой запрос по облигациям выдает больше записей (включая записи из предыдущего):
https://iss.moex.com/iss/securities.json?group_by=group&group_by_filter=stock_bonds

С чего правильно начинать?

**Comment by WLM1ke** [comment]
Зависит от того, что вы хотите получить. Я если честно постановку задачи не понимаю. Обычно торгуют в конкретном режиме торгов, поэтому я вообще пользуюсь запросом

https://iss.moex.com/iss/reference/32

**Comment by greg-kan** [comment]
Я хотел бы получить возможности:
1. Анализировать свой портфель, то, что уже есть в портфеле.
2. Выбирать новые инструменты, исходя из рыночных и исторических данных по ним.
В точности я пока не знаю, какую информацию нужно запрашивать - отсюда и исходит такой наивный вопрос.

Можно уточнить тогда следующее:
1. Что касается акций, то, насколько я успенл понять, в большинстве случаев можно ограничится режимом TQBR. Это правильно?
2. Как правильно ограничить выбор облигаций? Чтобы там были ОФЗ, муниципальные, корпораты из Российских. Там несколько досок. Запрашивать отдельным запросом по одной, или можно сделать запрос по группе бордов? И по какой группе?

Я понимаю, что вопросы не совсем корректные и конкрентые, но мне нужно как-то сориентироваться.
Спасибо Вам.

**Comment by WLM1ke** [comment]
По акция вы правы - основной режим торгов TQBR. В облигациях я не силен - не знаю. Перечень всех режимов торгов можно получить [запросиком](https://iss.moex.com/iss/index.json). Узнать нужный (подозреваю, что их может быть несколько отдельно для разных типов облигаций гос/корпоративных) можно на страничках соответствующих инструментов на сайте MOEX - например на первой попавшейся [сберовской](https://www.moex.com/ru/issue.aspx?board=TQCB&code=RU000A103WV8&utm_source=www.moex.com&utm_term=Сбербанк#/bond_1) указан режим TQCB, но тут лучше вам самому исследовать на примере нескольких облигаций, никогда не интересовался облигациями

**Comment by greg-kan** [comment]
Спасибо!

**Comment by WLM1ke** [comment]
> Спасибо!

Еще кстати вспомнил, если вас интересуют фонды, то это режим TQTF, рынок как и у акций shares
